### ISSUE TITLE
reading data from textinput

### ISSUE THREAD

**Issue by prashanthmadi** [dwicao/react-native-login-screen#1]
Thanks for writing this demo app.. i'm pretty new to react-native and was trying to utilize this demo app..

Could you help me retrieve values in UserInput after pressing submit button in ButtonSubmit.js file on login screen

**Comment by dwicao** [comment]
I think you must understand a concept of "Controlled Component" in React,  
this article explained it very well, please take a look http://lorenstewart.me/2016/10/31/react-js-forms-controlled-components/
