### ISSUE TITLE
Image Component in Wallpaper.js

### ISSUE THREAD

**Issue by manisha-sinha01** [dwicao/react-native-login-screen#11]
the image component of react native cannot have a child property. To have a prop to be displayed on the existing image, it should have <ImageBackground> component or absolute positioning.

**Comment by manisha-sinha01** [comment]
The problem can be solved by using 
<ImageBackground> tag instead of Image tag in react native because it wont support children inside <Image /> tag

**Comment by Yaweii** [comment]
@manisha-sinha01  sorry I don't quite understand your solution. I am facing the same issue now. Are you saying that we should not be using <Image> tag? If not, what do I need to use? Much appreciated!

**Comment by lunvjp** [comment]
The same here @manisha-sinha01 What do you really mean?
@Yaweii Have you done fixed this bug?
