### ISSUE TITLE
hello,i get this error,how can i solove it

### ISSUE THREAD

**Issue by NickTet** [dwicao/react-native-login-screen#6]
undefined is not an object (evaluating '_reactNative.ViewPropTypes.style')
<unknown>
    Scene.js:30
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    Actions.js:10
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    index.js:1
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    Main.js:2
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    index.android.js:4
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:116
_require
    require.js:107
global code
    require-0.js:1

**Comment by NickTet** [comment]
i solove  by change react version

**Comment by Hemantsolanki103** [comment]
Hi,
I have updated my react version but this problem is not resolved.

react-native-cli: 2.0.1
react-native: 0.44.0

Please help me to resolved this issues.

Thanks

**Comment by dwicao** [comment]
fixed in https://github.com/dwicao/react-native-login-screen/commit/9d8707c63bfd572c665dbfdf559cf40cfb3da8a3 please pull latest from master, thanks
