### ISSUE TITLE
it does not work for me, it throws me an error

### ISSUE THREAD

**Issue by MedinaGitHub** [dwicao/react-native-login-screen#9]
![error](https://user-images.githubusercontent.com/16387514/31078725-943356f2-a759-11e7-9a2d-c840eb6948ca.PNG)

**Comment by icreatesolutions** [comment]
I get the same

**Comment by antoniobenalcazar** [comment]
the same problem dude ! :(

**Comment by cmlyldz** [comment]
same problem...

**Comment by Abhith** [comment]
It worked for me after commenting [30 - 35 lines in the UserInput.js](https://github.com/dwicao/react-native-login-screen/blob/86a1f03e985c839e2678b3652c4c27ac3cbcf916/src/components/UserInput.js#L30).

i.e
```js
UserInput.propTypes = {
  // source: PropTypes.number.isRequired,
  // placeholder: PropTypes.string.isRequired,
  // secureTextEntry: PropTypes.bool,
  // autoCorrect: PropTypes.bool,
  // autoCapitalize: PropTypes.string,
  // returnKeyType: PropTypes.string,
};
```

**Comment by rrupsing** [comment]
You have to change the import for PropTypes to `import PropTypes from 'prop-types';`

**Comment by robinzhx** [comment]
Same issue

**Comment by im4eversmrt** [comment]
same issue here as well.

**Comment by giturra** [comment]
same issue

**Comment by giturra** [comment]
@rrupsing where is the file ? for the change the imports?

**Comment by rrupsing** [comment]
You may have to upgrade your React version! https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings

**Comment by Shhzdmrz** [comment]
this error came only when you are running app for production. because **ViewPropTypes.style** does not exist in production you need to use **View.propTypes.style** for production.

**Comment by szenciattila** [comment]
In package.json change **"react-native-router-flux": "^3.37.0"** to **"react-native-router-flux": "3.37.0"** and run "npm install" again.

**Comment by ToJen** [comment]
Also, use `import PropTypes from 'prop'types` instead of importing it from the `react` module.

**Comment by dwicao** [comment]
fixed in https://github.com/dwicao/react-native-login-screen/commit/9d8707c63bfd572c665dbfdf559cf40cfb3da8a3 please pull latest from master, thanks
